version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/GoodFriend.Plugin"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "yarn"
    directory: "/GoodFriend.Server"
    schedule:
      interval: "weekly"
