changes | localization:
  - "src/GoodFriend.Plugin/Resources/Localization/**/*"

changes | ci:
  - ".github/workflows/**/*"

changes | plugin:
  - "src/GoodFriend.Plugin/**/*.cs"

changes | server:
  - "src/GoodFriend.Server/**/*.cs"
