files:
  - source: /GoodFriend.Plugin/Resources/Localization/GoodFriend_Localizable.json
    translation: /%original_path%/%two_letters_code%.json
pull_request_title: "chore(i18n): Translation updates (Crowdin)
commit_message: "chore(i18n): translations updates for %two_letters_code%"
append_commit_message: false
