name: "PR: Server Code Changes"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "GoodFriend.Server/**"
    types: [ready_for_review, opened, synchronize]

jobs:
  Build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Post/Edit Initial Comment
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### Building ${{ github.repository}} (GoodFriend.Server) <span aria-hidden="true">🚧</span>
            Please wait, this could take several minutes to complete. This comment will be edited when finished.

            |  Name | Detail |
            |---------------------------------|-------------------------------------------------------------------------------------|
            | **Commit** 						          | ${{ github.sha }}                                                                   |
            | **Logs** 							          | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | **Build Environment** 			    | ${{ runner.os }}/${{ runner.arch }}                                                 |
            | **Triggered By**							  | [${{ github.actor }}](https://github.com/${{ github.actor }})                       |

            identifier: preview-build
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./GoodFriend.Server/
          file: ./GoodFriend.Server/Dockerfile
          push: false
          tags: testbuild/testbuild:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Edit Comment (Success)
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### Build Complete for ${{ github.repository }} (GoodFriend.Server) <span aria-hidden="true">⚡</span>
            All builds finished without issues and any artifact(s) have been uploaded.

            |  Name | Detail |
            |---------------------------------|------------------------------------------------------------------------------------|
            | **Commit** 						          | ${{ github.sha }}                                                                  |
            | **Logs** 							          | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|
            | **Build Environment** 			    | ${{ runner.os }}/${{ runner.arch }}                                                |
            | **Triggered By**							  | [${{ github.actor }}](https://github.com/${{ github.actor }})                      |

            identifier: preview-build
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Edit Comment (Failure)
        if: ${{ failure() }}
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
            ### Build Failed for ${{ github.repository }} (GoodFriend.Server) <span aria-hidden="true">⚠️</span>
            Something went wrong when running a build, please view the logs for more information about this.

            |  Name | Detail |
            |---------------------------------|-------------------------------------------------------------------------------------|
            | **Commit** 						          | ${{ github.sha }}                                                                   |
            | **Logs** 							          | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
            | **Build Environment** 			    | ${{ runner.os }}/${{ runner.arch }}                                                 |
            | **Triggered By**							  | [${{ github.actor }}](https://github.com/${{ github.actor }})                       |

            identifier: preview-build
          comment_includes: "preview-build"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
