name: "PR: Server Code Changes"

on:
  pull_request:
    branches: [ "main" ]
    paths: 
      - '**.ts'
      - '**Dockerfile'
      - '.github/workflows/pr_serversrc_changes.yml'    

jobs:
  Docker-Image-Build:
    runs-on: ubuntu-latest
    steps:
    - name: GitHub Checkout 
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: ./src/GoodFriend.Server/
        file: ./src/GoodFriend.Server/Dockerfile
        push: false
        tags: ${{ github.repository }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
